name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_folder:
        type: choice
        description: 'Select the suite of tests to run manually'
        required: true
        default: 'smoke' 
        options:
          - 'smoke'
          - 'regression'
          - 'all'

  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.test_folder }}" = "regression" ]; then
            echo "Executing REGRESSION suite manually..."
            npx playwright test tests/regression
          elif [ "${{ github.event.inputs.test_folder }}" = "all" ]; then
            echo "Executing ALL tests manually..."
            npx playwright test
          else
            echo "Executing SMOKE suite (Default or automatically activated)..."
            npx playwright test tests/smoke
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
