name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        type: choice
        description: 'Selecciona la etiqueta de pruebas a ejecutar manualmente'
        required: true
        default: 'smoke'
        options:
          - 'smoke'
          - 'regression'
          - 'all'

  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      APP_USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.test_suite }}" = "regression" ]; then
            echo "🚀 Ejecutando suite de REGRESSION manualmente..."
            npx playwright test --grep @regression
          elif [ "${{ github.event.inputs.test_suite }}" = "all" ]; then
            echo "🚀 Ejecutando TODO el proyecto manualmente..."
            npx playwright test
          else
            echo "🚀 Ejecutando suite de SMOKE (Por defecto o automático por cambio en código)..."
            npx playwright test --grep @smoke
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
