name: Playwright Tests

on:
  workflow_dispatch:
    # 1. Definimos el menú desplegable en GitHub
    inputs:
      test_folder:
        type: choice
        description: 'Selecciona la suite de pruebas a ejecutar'
        required: true
        default: 'all'
        options:
          - 'all'
          - 'smoke'
          - 'regression'

  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          USER: ${{ secrets.TEST_USER }} # Consejo: Cambiar USER a TEST_USER para evitar conflictos con Linux
          PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      # 2. Modificamos el comando de ejecución para leer la carpeta seleccionada
      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.test_folder }}" = "smoke" ]; then
            npx playwright test tests/smoke
          elif [ "${{ github.event.inputs.test_folder }}" = "regression" ]; then
            npx playwright test tests/regression
          else
            npx playwright test
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30